/**
 * @file    ota_aes_key.c
 * @brief   AES-256 pre-shared key storage for OTA firmware decryption
 * @author  GS_Mark
 *
 * WARNING: This key must match the key used by tools/firmware_sign.py
 *          (stored in tools/keys/aes_key.bin on the PC).
 *
 * Key generation: python tools/firmware_sign.py --genkey --keydir tools/keys/
 * The AES key is auto-generated on first sign operation.
 *
 * Production upgrade path:
 *   - STM32 Option Bytes for key storage (write-once)
 *   - ECDH key exchange for per-session keys
 *   - Secure element (ATECC608A, etc.)
 */

#include "ota_aes_key.h"

/*
 * AES-256 key (32 bytes).
 * Generated by: tools/firmware_sign.py (first --sign invocation)
 * Corresponds to: tools/keys/aes_key.bin
 *
 * Hex: 76fb72e286c9b0715f34f0f1f93fe5b6c51a34c08ded11d4b7e559a7d164911d
 */
static const uint8_t s_aes_key[32] = {
    0x76, 0xfb, 0x72, 0xe2, 0x86, 0xc9, 0xb0, 0x71,
    0x5f, 0x34, 0xf0, 0xf1, 0xf9, 0x3f, 0xe5, 0xb6,
    0xc5, 0x1a, 0x34, 0xc0, 0x8d, 0xed, 0x11, 0xd4,
    0xb7, 0xe5, 0x59, 0xa7, 0xd1, 0x64, 0x91, 0x1d,
};

const uint8_t *OtaAesKey_Get(void)
{
    return s_aes_key;
}
